site_name: Chromatix
repo_url: https://github.com/chromatix-team/chromatix/

nav:
  - Home: index.md
  - Hackathon: hackathon.md
  - Getting started:
    - Installing: installing.md
    - Chromatix 101: 101.ipynb
    - Polarization: polarization.ipynb
    - Parallelism: parallelism.md
    - Training: training.ipynb
    - Higher Rank Fields: higher_rank.ipynb
    - FAQ: FAQ.md
  - API:
    - Field: api/field.md
    - Functional: api/functional.md
    - Elements: api/elements.md
    - Systems: api/systems.md
    - Operations: api/ops.md
    - Utilities: api/utils.md
  - Examples:
    - Holoscope: examples/holoscope.ipynb
    - High NA lenses: examples/highNA_PSF.ipynb
    - Computer Generated Holography: examples/cgh.ipynb
    - Digital Micromirror Device: examples/dmd.ipynb
    - Scalable Angular Spectrum: examples/sas.ipynb
    - Bandlimited Angular Spectrum: examples/bandlimited_angular_spectrum.ipynb
    - Rescaled propagation: examples/rescaled_propagation.ipynb
    - Seidel Aberration Fitting: examples/seidel_fitting.ipynb
    - Zernike Aberration Fitting: examples/zernike_fitting.ipynb
    - Polarised multislice: examples/polarised_multislice.ipynb

theme:
  logo: media/logo_symbol_white.png
  favicon: media/favicon.png
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          heading_level: 3
          show_root_toc_entry: false
- mkdocs-jupyter
- search:
    separator: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
- css/mkdocstrings.css
